# Generated by Django 3.2.11 on 2022-05-11 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correduria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_correduria', models.CharField(max_length=200, null=True)),
                ('arengucode_agentcode', models.CharField(default='data-arengu-form-id=164926150512463762 data-field-agentcode=', max_length=200, null=True)),
                ('bbdd_embed_id', models.CharField(max_length=200, null=True)),
                ('nombre_view_airtable', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='usuariosxcorreduria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correduria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correduria', to='home.correduria')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Family',
        ),
    ]
