# Generated by Django 3.2.11 on 2022-07-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariosxcorreduria',
            name='staff',
            field=models.BooleanField(default=False),
        ),
    ]
