# Generated by Django 3.2.11 on 2022-07-22 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_usuariosxcorreduria_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariosxcorreduria',
            name='bbdd_total',
            field=models.BooleanField(default=False),
        ),
    ]
