# Generated by Django 3.2.11 on 2022-08-19 15:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_usuariosxcorreduria_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariosxcorreduria',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, max_length=200, null=True),
        ),
    ]
