# Generated by Django 3.2.11 on 2022-08-22 10:39

import apps.home.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0011_remove_usuariosxcorreduria_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='codigoDeSoporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoDeSoporte', models.CharField(default=apps.home.models.random_code, max_length=200)),
                ('expiryDate', models.DateField(default=apps.home.models.expiryDate)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Codigo de Soporte',
                'verbose_name_plural': 'Codigos de Soporte',
            },
        ),
    ]
