# Generated by Django 3.2.11 on 2022-08-22 10:41

import apps.home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_codigodesoporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigodesoporte',
            name='expiryDate',
            field=models.DateTimeField(default=apps.home.models.expiryDate),
        ),
    ]
