# Generated by Django 3.2.11 on 2022-09-07 11:28

import apps.home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_codigodesoporte_expirydate'),
    ]

    operations = [
        migrations.CreateModel(
            name='fileAnon',
            fields=[
                ('id', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('delete_id', models.CharField(max_length=1000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('expiryDate', models.DateTimeField(default=apps.home.models.fileAnonExpiryDate)),
            ],
            options={
                'verbose_name': 'Archivos anónimos',
                'verbose_name_plural': 'Archivos anónimos',
            },
        ),
        migrations.RemoveField(
            model_name='usuariosxcorreduria',
            name='correduria',
        ),
        migrations.RemoveField(
            model_name='usuariosxcorreduria',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Correduria',
        ),
        migrations.DeleteModel(
            name='usuariosxcorreduria',
        ),
    ]
