# Generated by Django 3.2.11 on 2022-09-08 10:43

import apps.home.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0014_auto_20220907_1128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileanon',
            options={'verbose_name': 'Archivo anónimo', 'verbose_name_plural': 'Archivos anónimos'},
        ),
        migrations.CreateModel(
            name='fileRegistered',
            fields=[
                ('id', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('delete_id', models.CharField(max_length=1000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('expiryDate', models.DateTimeField(default=apps.home.models.fileAnonExpiryDate)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Archivo de usuario registrado',
                'verbose_name_plural': 'Archivos de usuarios registrados',
            },
        ),
    ]
