# Generated by Django 3.2.11 on 2022-07-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalnotification',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
