# Generated by Django 3.2.11 on 2022-07-08 15:42

from django.db import migrations, models
import django_prometheus.models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_generalnotification_icono'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('mensaje', models.CharField(help_text='Mantenimiento programado para el día 27 de junio de 16:00 a 16:30 hrs.<br><a target="_blank" href="https://status.office.coventia.es/">Más información</a>', max_length=200, null=True)),
                ('disabled', models.BooleanField(default=False)),
            ],
            bases=(django_prometheus.models.ExportModelOperationsMixin('MaintenanceNotification'), models.Model),
        ),
    ]
