# Generated by Django 3.2.11 on 2022-07-08 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_maintenancenotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancenotification',
            name='mas_informacion_url',
            field=models.CharField(default='https://status.office.coventia.es/', max_length=300),
        ),
    ]
