# Generated by Django 3.2.11 on 2022-07-08 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_maintenancenotification_mas_informacion_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancenotification',
            name='mas_informacion_url',
            field=models.CharField(help_text='https://status.office.coventia.es/', max_length=300),
        ),
        migrations.AlterField(
            model_name='maintenancenotification',
            name='mensaje',
            field=models.CharField(help_text='Mantenimiento programado para el día 27 de junio de 16:00 a 16:30 hrs.', max_length=200, null=True),
        ),
    ]
