# Generated by Django 3.2.11 on 2022-09-05 10:20

from django.db import migrations, models
import django.db.models.deletion
import django_prometheus.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_codigodesoporte_expirydate'),
        ('notifications', '0007_auto_20220708_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='SegmentNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('icono', models.CharField(help_text='Ejemplo: lnil-save o lnil-list. <a target="_blank" href="https://huro.cssninja.io/elements-icons-lnil.html">Todos los ejemplos</a>', max_length=50)),
                ('mensaje', models.CharField(max_length=200, null=True)),
                ('fecha', models.DateTimeField()),
                ('disabled', models.BooleanField(default=False)),
                ('segment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.correduria')),
            ],
            bases=(django_prometheus.models.ExportModelOperationsMixin('SegmentNotification'), models.Model),
        ),
    ]
