# Generated by Django 3.2.11 on 2022-09-05 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_segmentnotification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SegmentNotification',
        ),
    ]
